# Generated by rstantools.  Do not edit by hand.

# names of stan models
.stanmodel_names <- c("mdcev", "mdcev_rp")

# load each stan module (always available — compiled into the package DLL)
Rcpp::loadModule("stan_fit4mdcev_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mdcev_rp_mod", what = TRUE)

# instantiate stanmodel objects only when rstan is available
if (requireNamespace("rstan", quietly = TRUE)) {
  stanmodels <- sapply(.stanmodel_names, function(model_name) {
    # create C++ code for stan model
    stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
    stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
    stanfit <- rstan::stanc_builder(stan_file,
                                    allow_undefined = TRUE,
                                    obfuscate_model_name = FALSE)
    stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                              model_cppcode = stanfit$cppcode)
    # create stanmodel object
    methods::new(Class = "stanmodel",
                 model_name = stanfit$model_name,
                 model_code = stanfit$model_code,
                 model_cpp = stanfit$model_cpp,
                 mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
  })
} else {
  stanmodels <- NULL
}

#' @title get_rstan_model
#' @description Retrieve a pre-compiled rstan stanmodel object by name.
#' @param model_name Character; one of "mdcev" or "mdcev_rp".
#' @return A stanmodel object.
#' @noRd
get_rstan_model <- function(model_name) {
  if (!requireNamespace("rstan", quietly = TRUE))
    stop("Package 'rstan' must be installed to use the rstan backend. ",
         "Install it with: install.packages('rstan')")
  if (is.null(stanmodels))
    stop("rstan stanmodel objects are not available. ",
         "Please restart R with rstan installed and reload rmdcev.")
  stanmodels[[model_name]]
}
