# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("mdcev", "mdcev_rp")

# load each stan module
Rcpp::loadModule("stan_fit4mdcev_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mdcev_rp_mod", what = TRUE)

# instantiate each stanmodel object (only if rstan is available)
if (requireNamespace("rstan", quietly = TRUE)) {
    tryCatch({
        stanmodels <- sapply(stanmodels, function(model_name) {
            # create C++ code for stan model
            stan_file <- if (dir.exists("stan")) "stan" else file.path("inst", "stan")
            stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
            stanfit <- rstan::stanc_builder(stan_file,
                                            allow_undefined = TRUE,
                                            obfuscate_model_name = FALSE)
            stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                                      model_cppcode = stanfit$cppcode)
            # create stanmodel object
            methods::new(Class = "stanmodel",
                         model_name = stanfit$model_name,
                         model_code = stanfit$model_code,
                         model_cpp = stanfit$model_cpp,
                         mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
        })
    }, error = function(e) {
        warning("Failed to initialize rstan stanmodel objects: ", conditionMessage(e),
                ". The rstan backend and hessian computation will not be available.",
                call. = FALSE)
        stanmodels <<- list()
    })
} else {
    stanmodels <- list()
}

